// Copyright (c) 2026 TypeDreamMoon. All rights reserved.
//
// Node <-> source line navigation (plan §13.2, contract §5 row N).
//
// A 2.0 compile stamps every generated asset with a `DreamShader.SourceSpans` metadata table --
// `{ "<ExpressionGuid>": { "file", "line", "col", "len", "callLine", "callCol" } }`, written by
// DreamShaderIREmitter's WriteDreamShaderSourceSpans (unit E, contract §2 decision §11 #10). This
// file is the only reader of that table, and it turns it into the two directions of navigation:
//
//   graph -> source  the material editor's node context menu grows *DreamShader > Open Source Line*
//                    (and *Open Call Site* for a node that came from an inlined helper), opening the
//                    file through the existing preferred-editor launcher.
//   source -> graph  the bridge request `reveal-node { file, line }` finds the assets generated from
//                    that source, picks the expression(s) whose span covers the line, opens the
//                    material editor and calls IMaterialEditor::JumpToExpression.
//
// Why the table is read through the package metadata and not off the node: `Desc` was rejected (a
// per-node comment bubble on every generated node), and the graph the material editor shows is a
// TRANSIENT DUPLICATE of the asset -- FMaterialEditor::DuplicatePreviewMaterial for a material, a
// StaticDuplicateObject of the function for a function editor -- so the object under the cursor has
// no package metadata at all. What duplication DOES preserve is UMaterialExpression::
// MaterialExpressionGuid (a plain UPROPERTY), which is why the guid, not the object, is the key.

#pragma once

#include "CoreMinimal.h"

#include "Diagnostics/DreamShaderDiagnosticsStore.h"

class FJsonObject;
class UMaterialExpression;
class UObject;

namespace UE::DreamShader::Lang
{
	class FLangDiagnosticSink;
}

namespace UE::DreamShader::Editor::Private
{
	/**
	 * One row of `DreamShader.SourceSpans`: where the expression carrying this guid came from.
	 *
	 * Line/Column are 1-based, as everywhere else in the diagnostics wire. Length is the span's
	 * length in TCHARs (the emitter copies Lang::FLangSpan::Length), kept because a language service
	 * wants to select the expression, not just put the caret in front of it.
	 *
	 * CallLine/CallColumn are the call site of the helper the node was inlined from (contract §6.4:
	 * every node made while inlining carries Source.CallSite). They are 0 when the node was not
	 * inlined, which is what HasCallSite() answers -- a call site is never at line 0.
	 */
	struct FDreamShaderSourceSpan
	{
		/** The file the span points into, as the compiler spelled it. Absolute, or project-relative. */
		FString File;
		int32 Line = 1;
		int32 Column = 1;
		int32 Length = 0;
		/**
		 * The file the CALL SITE is in, when it differs from File.
		 *
		 * Optional: IR::FIRSourceRef carries CallSiteFile alongside File (CONTRACT 6.13 #6), and
		 * WriteDreamShaderSourceSpans emits `callFile` only when the two differ -- a helper defined
		 * in an imported `.dsh` and called from a `.dss` is exactly that case. Empty here means the
		 * same file as File, which is every same-file inline.
		 */
		FString CallFile;
		int32 CallLine = 0;
		int32 CallColumn = 0;

		bool IsValid() const { return !File.IsEmpty() && Line >= 1; }
		bool HasCallSite() const { return CallLine >= 1; }

		/** File as an absolute normalized path, resolving a project-relative stamp like the metadata does. */
		FString GetAbsoluteFilePath() const;
		/** The call site file the same way; falls back to GetAbsoluteFilePath() when CallFile is empty. */
		FString GetAbsoluteCallSiteFilePath() const;
	};

	/**
	 * The parsed `DreamShader.SourceSpans` table of one asset.
	 *
	 * Loading never fails loudly: an asset with no table (hand-authored, or generated by the 1.x
	 * generator, which does not write one) yields an empty table, and IsEmpty() is the question every
	 * caller actually asks. A table that IS present but malformed raises DSH9053 on the sink when one
	 * is given, so the failure has a code rather than looking like "this asset has no navigation".
	 */
	class FDreamShaderSourceSpanTable
	{
	public:
		/** The package metadata key. Same string on the writing side (unit E). */
		static const TCHAR* GetMetadataKey();

		/**
		 * The object whose package metadata holds the table for Asset.
		 *
		 * That is Asset itself for a UMaterial / UMaterialFunction. For a material INSTANCE -- the
		 * ThinCustom backend's addressable asset -- the graph and therefore the table live on the
		 * hidden base material, so the parent chain is walked up to the first UMaterial. Returns
		 * nullptr when there is no such object.
		 */
		static UObject* ResolveTableOwner(UObject* Asset);

		/** Reads + parses the table off Asset (or its hidden base). Empty when the asset has none. */
		static FDreamShaderSourceSpanTable LoadFromAsset(UObject* Asset, Lang::FLangDiagnosticSink* Sink = nullptr);

		/** Parses the JSON form directly. Exposed for the tests and for a caller that already has the text. */
		static FDreamShaderSourceSpanTable ParseJson(const FString& JsonText, const FString& AssetPathForMessages, Lang::FLangDiagnosticSink* Sink = nullptr);

		bool IsEmpty() const { return Spans.IsEmpty(); }
		int32 Num() const { return Spans.Num(); }
		const TMap<FGuid, FDreamShaderSourceSpan>& GetSpans() const { return Spans; }

		/** The asset the table was read from (the hidden base, when it was reached through one). */
		UObject* GetOwningAsset() const { return OwningAsset.Get(); }

		const FDreamShaderSourceSpan* Find(const FGuid& ExpressionGuid) const { return Spans.Find(ExpressionGuid); }
		const FDreamShaderSourceSpan* FindForExpression(const UMaterialExpression* Expression) const;

		/**
		 * Every guid whose span names File and covers Line.
		 *
		 * `OutOnLine` are the nodes whose span STARTS on that line -- what the caller wants to select.
		 * `OutViaCallSite` are the nodes of an inlined helper whose CALL is on that line (contract §6.4).
		 * `OutCovering` are the nodes whose span starts earlier and may reach the line (a `@custom`
		 * body); the table records a character length and not an end line, so this one is a bounded
		 * guess and is meant to be consulted only when the other two are empty.
		 *
		 * The three are disjoint, and each is totally ordered (column or distance, then guid), so "the
		 * first one" is the same answer on every run.
		 */
		void FindByLine(
			const FString& File,
			int32 Line,
			TArray<FGuid>& OutOnLine,
			TArray<FGuid>& OutCovering,
			TArray<FGuid>& OutViaCallSite) const;

	private:
		TMap<FGuid, FDreamShaderSourceSpan> Spans;
		TWeakObjectPtr<UObject> OwningAsset;
	};

	/**
	 * The span recorded for one expression, found wherever it lives.
	 *
	 * The expression handed in is usually the material editor's transient duplicate, so its own outer
	 * has no metadata; the guid is looked up in the table of every loaded generated asset. OutAsset
	 * receives the asset whose table answered. False when no table knows the guid.
	 */
	bool FindDreamShaderSourceSpanForExpression(
		const UMaterialExpression* Expression,
		FDreamShaderSourceSpan& OutSpan,
		UObject*& OutAsset);

	/** Opens File at Line/Column through FDreamShaderEditorLaunchUtils::LaunchTextFileInPreferredEditor. Toasts + logs a failure (DSH9058). */
	bool OpenDreamShaderSourceLocation(const FString& File, int32 Line, int32 Column);

	/**
	 * The *DreamShader > Open Source Line* extension of the material editor's graph-node context menu.
	 *
	 * Registered from DreamShaderEditorModule::StartupModule through UToolMenus::RegisterStartupCallback,
	 * the same way the Material Content Browser registers its entries. Both calls are idempotent.
	 */
	struct FDreamShaderSourceNavigationMenu
	{
		static void Register();
		static void Unregister();
	};

	/** The answer to one `reveal-node` request, before it is written out. */
	struct FDreamShaderRevealNodeResult
	{
		bool bOk = false;
		/** Invariant wire text; the localised FText is what Message was built from. */
		FText Message;
		/** The asset whose graph was revealed. Empty on failure. */
		FString AssetPath;
		/** The instance the asset was reached through, when it is a ThinCustom hidden base. */
		FString InstanceAssetPath;
		/** Every expression the request matched; the first one is the one that was jumped to. */
		TArray<FGuid> ExpressionGuids;
		/** DSH9050-9057 for a failure; empty on success. */
		TArray<FDreamShaderDiagnosticRecord> Diagnostics;
	};

	/**
	 * Serves one `reveal-node { "file": "<source path>", "line": N }` request.
	 *
	 * Game thread only: it opens an asset editor. Never throws and never leaves the editor in a
	 * half-open state -- every refusal comes back as a diagnostic in the result.
	 */
	FDreamShaderRevealNodeResult HandleDreamShaderRevealNodeRequest(const FJsonObject& Request);

	/**
	 * Writes `Responses/<RequestId>.json` for a reveal-node answer.
	 *
	 * Separate from the bridge's RespondTo because this response carries `assetPath` and
	 * `expressions`, which RespondTo's signature has no room for; every field RespondTo writes is
	 * written here too, in the same order, so a client parses one shape. A request without an id is
	 * not answered, exactly as RespondTo does it.
	 */
	void WriteDreamShaderRevealNodeResponse(
		const FString& RequestId,
		const FString& ResponseDirectory,
		const FDreamShaderRevealNodeResult& Result,
		double DurationMs);
}
