#include "DreamShaderPassModule.h"

#include "DreamShaderModule.h"

#include "HAL/FileManager.h"
#include "HAL/PlatformProperties.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

#if DREAMSHADER_WITH_CUSTOM_PASS
#include "Render/DreamPassSceneViewExtension.h"
#endif

DEFINE_LOG_CATEGORY(LogDreamPass);

namespace UE::DreamPass
{
	const FString& GetUserShaderVirtualDirectory()
	{
		static const FString VirtualDirectory = TEXT("/DreamPassUser");
		return VirtualDirectory;
	}

	FString GetUserShaderDirectory()
	{
		// The project root only: a plugin's DShader folder is read-only to the editor, and the global shaders are one
		// set per project, so a plugin's `.dsp` gets its slots in the project's registry like any other.
		return FPaths::Combine(UE::DreamShader::GetSourceShaderDirectory(), TEXT(".dreampass"));
	}

	FString GetRegistryFilePath(bool bCompute)
	{
		return FPaths::Combine(GetUserShaderDirectory(), bCompute ? TEXT("RegistryCompute.ush") : TEXT("RegistryPixel.ush"));
	}

	static FString GetSlotLeaf(bool bCompute, int32 Slot)
	{
		return FString::Printf(TEXT("%c%02d"), bCompute ? TCHAR('C') : TCHAR('P'), Slot);
	}

	FString GetSlotDirectory(bool bCompute, int32 Slot)
	{
		return FPaths::Combine(GetUserShaderDirectory(), TEXT("Slots"), GetSlotLeaf(bCompute, Slot));
	}

	FString GetSlotVirtualDirectory(bool bCompute, int32 Slot)
	{
		return GetUserShaderVirtualDirectory() / TEXT("Slots") / GetSlotLeaf(bCompute, Slot);
	}

	FString MakeEmptyRegistryText(bool bCompute)
	{
		return FString::Printf(
			TEXT("// DreamShader Custom Pass -- %s slot registry.\n")
			TEXT("//\n")
			TEXT("// Generated by DreamShaderCompiler. No slot is defined, so every slot compiles to its empty stub.\n")
			TEXT("// Commit this file and the Slots folder next to it: the global shaders are built from them.\n"),
			bCompute ? TEXT("compute") : TEXT("pixel"));
	}

	/**
	 * Takes out of one registry every slot section whose snapshot is not on disk. The registry includes each live slot's
	 * snapshot, and a missing include fails the global shader compile at startup -- which is fatal -- so a Slots folder
	 * that was not committed, or a merge that kept the registry but not its files, would stop the editor. A section taken
	 * out leaves its slot to the stub: its pass does nothing until its `.dsp` is compiled again, which writes the snapshot
	 * and the section back (`dsc pass-registry -Rebuild` does every one). Registry.json is the compiler's and stays as it is.
	 */
	static void DropSectionsWithMissingSnapshots(bool bCompute)
	{
		const FString RegistryPath = GetRegistryFilePath(bCompute);
		FString Text;
		if (!FFileHelper::LoadFileToString(Text, *RegistryPath))
		{
			return;
		}

		TArray<FString> Lines;
		Text.ParseIntoArrayLines(Lines, /*bCullEmpty*/ false);

		// A section, as the compiler writes it: `#if DP_SLOT == N`, defines, one `#include "/DreamPassUser/Slots/..."`,
		// undefs, `#endif` -- never a nested #if, the snapshot being a file of its own.
		const FString UserPrefix = GetUserShaderVirtualDirectory() + TEXT("/");
		TArray<FString> Kept;
		TArray<FString> Section;
		TArray<FString> Missing;
		bool bInSection = false;
		bool bSectionMissing = false;
		for (const FString& Line : Lines)
		{
			const FString Trimmed = Line.TrimStartAndEnd();
			if (!bInSection && Trimmed.StartsWith(TEXT("#if DP_SLOT")))
			{
				bInSection = true;
				bSectionMissing = false;
				Section.Reset();
			}
			if (!bInSection)
			{
				Kept.Add(Line);
				continue;
			}

			Section.Add(Line);
			int32 FirstQuote = INDEX_NONE;
			int32 LastQuote = INDEX_NONE;
			if (Trimmed.StartsWith(TEXT("#include")) && Trimmed.FindChar(TCHAR('"'), FirstQuote) && Trimmed.FindLastChar(TCHAR('"'), LastQuote) && LastQuote > FirstQuote)
			{
				const FString IncludePath = Trimmed.Mid(FirstQuote + 1, LastQuote - FirstQuote - 1);
				if (IncludePath.StartsWith(UserPrefix)
					&& !IFileManager::Get().FileExists(*FPaths::Combine(GetUserShaderDirectory(), IncludePath.RightChop(UserPrefix.Len()))))
				{
					bSectionMissing = true;
					Missing.Add(IncludePath);
				}
			}
			if (Trimmed.StartsWith(TEXT("#endif")))
			{
				bInSection = false;
				if (!bSectionMissing)
				{
					Kept.Append(Section);
				}
			}
		}
		// A section the file ends inside is left as it was: not ours to guess at.
		if (bInSection)
		{
			Kept.Append(Section);
		}

		if (Missing.IsEmpty())
		{
			return;
		}

		const FString Rewritten = FString::Join(Kept, TEXT("\n")) + TEXT("\n");
		if (!FFileHelper::SaveStringToFile(Rewritten, *RegistryPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			UE_LOG(LogDreamPass, Error, TEXT("DreamShaderPass: %s includes snapshots that are not on disk (%s), and could not be rewritten without them; the slot shaders will fail to compile. Restore DShader/.dreampass/Slots, or delete the registry files to start over."),
				*RegistryPath, *FString::Join(Missing, TEXT(", ")));
			return;
		}
		UE_LOG(LogDreamPass, Error, TEXT("DreamShaderPass: %s included snapshots that are not on disk (%s): their slots were taken out so the slot shaders compile, and their passes do nothing until their .dsp files are compiled again (dsc pass-registry -Rebuild). Commit DShader/.dreampass/ with your sources."),
			*RegistryPath, *FString::Join(Missing, TEXT(", ")));
	}

	static void EnsureUserShaderDirectory()
	{
		IFileManager& FileManager = IFileManager::Get();
		const FString Directory = GetUserShaderDirectory();
		FileManager.MakeDirectory(*FPaths::Combine(Directory, TEXT("Slots")), true);

		// The registries are included by the slot shaders unconditionally, and AddShaderSourceDirectoryMapping
		// asserts the directory exists, so both files exist before the mapping is made -- empty, until the compiler
		// gives a pass a slot.
		for (const bool bCompute : { true, false })
		{
			const FString RegistryPath = GetRegistryFilePath(bCompute);
			if (!FileManager.FileExists(*RegistryPath))
			{
				FFileHelper::SaveStringToFile(MakeEmptyRegistryText(bCompute), *RegistryPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
			}
			else
			{
				DropSectionsWithMissingSnapshots(bCompute);
			}
		}
	}
}

void FDreamShaderPassModule::StartupModule()
{
#if DREAMSHADER_WITH_CUSTOM_PASS
	// PostConfigInit, as every module that registers shader types or shader directories must be: the global shader
	// types in Render/DreamPassGlobalShaders.cpp register from their static initializers when this DLL loads, and
	// the engine commits the shader type list right after the PostConfigInit modules (RC/Private/Shader.cpp:313).
	// The mapping is skipped in cooked builds, where the engine reads no shader source and refuses the call.
	if (!FPlatformProperties::RequiresCookedData())
	{
		UE::DreamPass::EnsureUserShaderDirectory();

		const FString& VirtualDirectory = UE::DreamPass::GetUserShaderVirtualDirectory();
		if (!AllShaderSourceDirectoryMappings().Contains(VirtualDirectory))
		{
			AddShaderSourceDirectoryMapping(VirtualDirectory, UE::DreamPass::GetUserShaderDirectory());
		}
	}
#else
	UE_LOG(LogDreamPass, Log, TEXT("DreamShaderPass: Custom Pass needs Unreal Engine 5.8 or later; this build has the asset types only."));
#endif
}

void FDreamShaderPassModule::ShutdownModule()
{
#if DREAMSHADER_WITH_CUSTOM_PASS
	FDreamPassSceneViewExtension::RemovePostOpaqueHandler();
#endif
}

IMPLEMENT_MODULE(FDreamShaderPassModule, DreamShaderPass);
