#include "DreamShaderPassModule.h"

#include "DreamShaderModule.h"

#include "HAL/FileManager.h"
#include "HAL/PlatformProperties.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

DEFINE_LOG_CATEGORY(LogDreamPass);

namespace UE::DreamPass
{
	const FString& GetUserShaderVirtualDirectory()
	{
		static const FString VirtualDirectory = TEXT("/DreamPassUser");
		return VirtualDirectory;
	}

	FString GetUserShaderDirectory()
	{
		// The project root only: a plugin's DShader folder is read-only to the editor, and the global shaders are one
		// set per project, so a plugin's `.dsp` gets its slots in the project's registry like any other.
		return FPaths::Combine(UE::DreamShader::GetSourceShaderDirectory(), TEXT(".dreampass"));
	}

	FString GetRegistryFilePath(bool bCompute)
	{
		return FPaths::Combine(GetUserShaderDirectory(), bCompute ? TEXT("RegistryCompute.ush") : TEXT("RegistryPixel.ush"));
	}

	static FString GetSlotLeaf(bool bCompute, int32 Slot)
	{
		return FString::Printf(TEXT("%c%02d"), bCompute ? TCHAR('C') : TCHAR('P'), Slot);
	}

	FString GetSlotDirectory(bool bCompute, int32 Slot)
	{
		return FPaths::Combine(GetUserShaderDirectory(), TEXT("Slots"), GetSlotLeaf(bCompute, Slot));
	}

	FString GetSlotVirtualDirectory(bool bCompute, int32 Slot)
	{
		return GetUserShaderVirtualDirectory() / TEXT("Slots") / GetSlotLeaf(bCompute, Slot);
	}

	FString MakeEmptyRegistryText(bool bCompute)
	{
		return FString::Printf(
			TEXT("// DreamShader Custom Pass -- %s slot registry.\n")
			TEXT("//\n")
			TEXT("// Generated by DreamShaderCompiler. No slot is defined, so every slot compiles to its empty stub.\n")
			TEXT("// Commit this file and the Slots folder next to it: the global shaders are built from them.\n"),
			bCompute ? TEXT("compute") : TEXT("pixel"));
	}

	static void EnsureUserShaderDirectory()
	{
		IFileManager& FileManager = IFileManager::Get();
		const FString Directory = GetUserShaderDirectory();
		FileManager.MakeDirectory(*FPaths::Combine(Directory, TEXT("Slots")), true);

		// The registries are included by the slot shaders unconditionally, and AddShaderSourceDirectoryMapping
		// asserts the directory exists, so both files exist before the mapping is made -- empty, until the compiler
		// gives a pass a slot.
		for (const bool bCompute : { true, false })
		{
			const FString RegistryPath = GetRegistryFilePath(bCompute);
			if (!FileManager.FileExists(*RegistryPath))
			{
				FFileHelper::SaveStringToFile(MakeEmptyRegistryText(bCompute), *RegistryPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
			}
		}
	}
}

void FDreamShaderPassModule::StartupModule()
{
#if DREAMSHADER_WITH_CUSTOM_PASS
	// PostConfigInit, as every module that registers shader types or shader directories must be: the global shader
	// types in Render/DreamPassGlobalShaders.cpp register from their static initializers when this DLL loads, and
	// the engine commits the shader type list right after the PostConfigInit modules (RC/Private/Shader.cpp:313).
	// The mapping is skipped in cooked builds, where the engine reads no shader source and refuses the call.
	if (!FPlatformProperties::RequiresCookedData())
	{
		UE::DreamPass::EnsureUserShaderDirectory();

		const FString& VirtualDirectory = UE::DreamPass::GetUserShaderVirtualDirectory();
		if (!AllShaderSourceDirectoryMappings().Contains(VirtualDirectory))
		{
			AddShaderSourceDirectoryMapping(VirtualDirectory, UE::DreamPass::GetUserShaderDirectory());
		}
	}
#else
	UE_LOG(LogDreamPass, Log, TEXT("DreamShaderPass: Custom Pass needs Unreal Engine 5.8 or later; this build has the asset types only."));
#endif
}

void FDreamShaderPassModule::ShutdownModule()
{
}

IMPLEMENT_MODULE(FDreamShaderPassModule, DreamShaderPass);
