// Copyright (c) 2026 TypeDreamMoon. All rights reserved.
//
// Glyphs, colours and labels for the browser's status values, shared by the source list rows and
// the inspector so a status looks the same everywhere it is drawn.

#pragma once

#include "CoreMinimal.h"
#include "Internationalization/Text.h"
#include "Math/Color.h"
#include "UI/Model/DreamShaderBrowserEntry.h"

namespace UE::DreamShader::Editor::Private
{
	struct FBrowserStatusVisual
	{
		FText Glyph;
		FLinearColor Color;
		FText Label;
	};

	inline const FLinearColor BrowserErrorColor(0.82f, 0.24f, 0.22f);
	inline const FLinearColor BrowserLinkColor(0.35f, 0.55f, 0.85f);

	inline FBrowserStatusVisual GetBrowserStatusVisual(EBrowserSourceStatus Status)
	{
		switch (Status)
		{
		case EBrowserSourceStatus::UpToDate:
			return { INVTEXT("●"), FLinearColor(0.10f, 0.62f, 0.20f), NSLOCTEXT("DreamShaderMaterialBrowser", "StatusUpToDate", "up to date") };
		case EBrowserSourceStatus::Stale:
			return { INVTEXT("●"), FLinearColor(0.90f, 0.62f, 0.12f), NSLOCTEXT("DreamShaderMaterialBrowser", "StatusStale", "stale") };
		case EBrowserSourceStatus::InMemoryUntracked:
			return { INVTEXT("◐"), FLinearColor(0.10f, 0.62f, 0.20f), NSLOCTEXT("DreamShaderMaterialBrowser", "StatusInMemoryUntracked", "compiled in memory") };
		case EBrowserSourceStatus::NotCompiled:
			return { INVTEXT("○"), FLinearColor(0.50f, 0.50f, 0.50f), NSLOCTEXT("DreamShaderMaterialBrowser", "StatusNever", "not compiled") };
		case EBrowserSourceStatus::Error:
			return { INVTEXT("▲"), BrowserErrorColor, NSLOCTEXT("DreamShaderMaterialBrowser", "StatusError", "compile error") };
		case EBrowserSourceStatus::Library:
			return { INVTEXT("◆"), FLinearColor(0.30f, 0.52f, 0.82f), NSLOCTEXT("DreamShaderMaterialBrowser", "StatusFunction", "function / header") };
		default:
			return { INVTEXT("▲"), BrowserErrorColor, NSLOCTEXT("DreamShaderMaterialBrowser", "StatusUnresolved", "unresolved") };
		}
	}

	inline FText GetBrowserProvenanceLabel(EDreamShaderDigestState State)
	{
		switch (State)
		{
		case EDreamShaderDigestState::Generated:
			return NSLOCTEXT("DreamShaderMaterialBrowser", "ProvenanceGenerated", "generated (matches the last build)");
		case EDreamShaderDigestState::Diverged:
			return NSLOCTEXT("DreamShaderMaterialBrowser", "ProvenanceDiverged", "edited by hand since the last build");
		case EDreamShaderDigestState::Unstamped:
			return NSLOCTEXT("DreamShaderMaterialBrowser", "ProvenanceUnstamped", "generated (no comparable digest)");
		default:
			return NSLOCTEXT("DreamShaderMaterialBrowser", "ProvenanceForeign", "not generated by DreamShader");
		}
	}

	inline FText GetBrowserStorageLabel(EBrowserStorage Storage)
	{
		return Storage == EBrowserStorage::InMemory
			? NSLOCTEXT("DreamShaderMaterialBrowser", "InMemory", "memory-only (not saved)")
			: NSLOCTEXT("DreamShaderMaterialBrowser", "OnDisk", "on disk");
	}

	inline bool IsBrowserErrorStatus(EBrowserSourceStatus Status)
	{
		return Status == EBrowserSourceStatus::Error || Status == EBrowserSourceStatus::Unresolved;
	}
}
